# Configuration for Request Handling System
system:
  batch_size: 1                # Number of requests processed in a batch
  cache_interval: 5            # Interval for cache expiration in timesteps

server:
  url: "http://localhost:8000"

client:
  poll_interval: 8             # Interval for polling for completed requests

model:
  model_path: "/home/DiTServing/stability_sd3_infer/models/sd3_medium.safetensors"
  model_folder: "/home/DiTServing/stability_sd3_infer/models/"

  